#======================================#
#========== Server settings ===========#
#======================================#
server:
  port: 80
  servlet:
    context-path: /   # 应用程序名称
  tomcat:
    uri-encoding: UTF-8
    
#======================================#
#========== Spring settings ===========#
#======================================#
spring:
  profiles:
    active: core #包含core配置文件

  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/shiva-maybe?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  # javamail配置
  mail:
    # 配置一个邮箱，username表示发送人
    host: smtp.qq.com
    port: 465
    username: 506230116@qq.com
    password: fsqylsyyplmubhjj
    properties:
      mail:
        smtp:
          ssl:
            enable: true #一定要开启ssl,不然会503 验证失败的


#======================================#
#========== project settings ==========#
#======================================#

# 系统自定义参数配置
maybe:
  # 控制台主页路径
  consolePath: /overall/console
  # 文件上传路径
  uploadFilePath: maybe/upload/
